#cloud-config
autoinstall:
  version: 1
  interactive-sections: ["*"]
  early-commands:
    - [timeout, "30", sh, -c, 'while [ -z "$(ip route show default)" ]; do sleep 1; done']
    - apt update
    - apt install -y nvme-cli
